### ISSUE TITLE
Running the test has no effect

### ISSUE THREAD

**Issue by z411500976** [shutterstock/changeDPI#13]
The image in the test file has not changed since the conversion. I don't know why.

**Comment by asturur** [comment]
Hi @z411500976  can you specify what do you mean exactly?
What operations do you execute and what you expect to happen but it doesn't.

**Comment by z411500976** [comment]
I am very glad that you can reply in time. I want to change the DPI of the picture. After running npm run test, the picture DPI in test has not changed.The DPI of ‘jpeg456-1.jpg’ has not become 300.
![image](https://user-images.githubusercontent.com/24216715/62681344-122efb00-b9ec-11e9-93cc-233a466cefaf.png)

**Comment by asturur** [comment]
how are you inspecting the file?

**Comment by z411500976** [comment]
Hi ，With photoshop view, is the display in PS incorrect?I need Image for print 300 dpi, for photo album

**Comment by z411500976** [comment]
In fact, the picture is 300 DPI, but the picture exif has not changed?

**Comment by z411500976** [comment]
Now I find that using your project image has no effect. I can work with my image. Why?
