### ISSUE TITLE
Using with image/png

### ISSUE THREAD

**Issue by radykal** [shutterstock/changeDPI#3]
Is it correct that you can only use jpeg, I am trying to use this project with data urls encoded in image/png?!

**Comment by asturur** [comment]
Hi @radykal, it works with pngs too.

Did you encounter some problem trying to make it work?

**Comment by radykal** [comment]
removepHYs is not defined.
`removepHYs = true;`

I checked your code and its not defined with var. This is caused by strict mode.

**Comment by asturur** [comment]
i ll check it and fix it, thanks.

**Comment by asturur** [comment]
I think the code in DIST is not updated. that removepHYs is an overwritepHYs.

I'll rebuild the lib and republish the npm package.

**Comment by hiddestokvis** [comment]
@asturur did you get around to updating the NPM package? I am still encountering this issue

**Comment by asturur** [comment]
i could not republish yet, i should be able to do it today.

**Comment by asturur** [comment]
i just published 1.0.3 with the file rebuilt, sorry for the confusion in the first place.
Let us know possible improvement or difficulties with the lib.
