### ISSUE TITLE
changeDpiDataUrl() sometimes returns invalid PNGs.

### ISSUE THREAD

**Issue by remig** [shutterstock/changeDPI#6]
When I pass the attached PNG image in changeDpiDataUrl(), it returns an invalid PNG.  It's easy to reproduce:
```javascript
var res = changeDpiDataUrl(attached_png, 300);
```
'res' will be a badly formed PNG image.

I don't fully understand the code, but it looks like detectPhysChunkFromDataUrl() cannot find what it's looking for, so it returns -1.  The calling code checks if the return value is truthy; -1 is, so the header length calculation is wrong.

[base64_png.txt](https://github.com/shutterstock/changeDPI/files/2247927/base64_png.txt)

**Comment by asturur** [comment]
Hi Remi,
can i ask you how did you generate that base64?

Does it comes from a html5 Canvas or some other source?

**Comment by remig** [comment]
Sorry, I should have included a full repro.  Attached is a standalone page that shows the problem.  'bundle.js' is the simple repro, bundle_compiled. is just bundle.js run through webpack.

The repro creates one HTML5 canvas and two images.  The first image.src is set to the result of canvas.toDataURL(). The second image.src is set to the result of changeDpiDataUrl( canvas.toDataURL(), 300).

For me, the second image shows a broken image icon.  I tried this in the latest Chrome & Firefox on Windows 7.  I get the same result regardless of DPI setting passed to changeDpiDataUrl, and regardless of canvas content.

[repro.zip](https://github.com/shutterstock/changeDPI/files/2249802/repro.zip)

**Comment by asturur** [comment]
Ok thanks for the test case. I needed just to know if it was a canvas generated png or generated from other softwares (photoshop, or similars, or downloaded from the interet).

I ll look into it asap. I have seen your fix, i want just to verify why it fails and why i wrote that code originally.

**Comment by remig** [comment]
I doubt my fix is ideal, but it solves this particular problem, and might point to a better fix.  Thanks for looking into it!
