### ISSUE TITLE
I'm unable to generate 300DPI while my image type is image/png. I have used latest release.

### ISSUE THREAD

**Issue by DhawalK09** [shutterstock/changeDPI#9]

**Comment by asturur** [comment]
hi @dhawalk09, can you show some code on how you are using it?

thanks.

**Comment by DhawalK09** [comment]
hi @asturur sorry for late revert.
I did this  
var Base64= canvas.toDataURL('image/png', 0.92)
 var daurl300dpi = changeDpiDataUrl(Base64, 300);
var link = document.createElement("a");
 link.setAttribute("style", "display:none;");
link.download = "chart.png";
link.href=daurl300dpi ;
 link.click();


I'm able to get 300 DPI for 'image/jpeg' but when i did "canvas.toDataURL('image/png', 0.92)" It returns only 96 DPI Image.
Please help me out with this.
Thanks.



I changed a bit to main code as i was having issue with my js minification due to const and let so  i changed it to var


//ChangeDPIDataURLFunction 
function createPngDataTable() {
    /* Table of CRCs of all 8-bit messages. */
    var crcTable = new Int32Array(256);
    for (var n = 0; n < 256; n++) {
        var c = n;
        for (var k = 0; k < 8; k++) {
            c = (c & 1) ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
        }
        crcTable[n] = c;
    }
    return crcTable;
}

function calcCrc(buf) {
    var c = -1;
    if (!pngDataTable) pngDataTable = createPngDataTable();
    for (var n = 0; n < buf.length; n++) {
        c = pngDataTable[(c ^ buf[n]) & 0xFF] ^ (c >>> 8);
    }
    return c ^ -1;
}
var pngDataTable;

var PNG = 'image/png';
var JPEG = 'image/jpeg';

// those are 3 possible signature of the physBlock in base64.
// the pHYs signature block is preceed by the 4 bytes of lenght. The length of
// the block is always 9 bytes. So a phys block has always this signature:
// 0 0 0 9 p H Y s.
// However the data64 encoding aligns we will always find one of those 3 strings.
// this allow us to find this particular occurence of the pHYs block without
// converting from b64 back to string
var b64PhysSignature1 = 'AAlwSFlz';
var b64PhysSignature2 = 'AAAJcEhZ';
var b64PhysSignature3 = 'AAAACXBI';

var _P = 'p'.charCodeAt(0);
var _H = 'H'.charCodeAt(0);
var _Y = 'Y'.charCodeAt(0);
var _S = 's'.charCodeAt(0);

function _toConsumableArray(arr) {
    if (Array.isArray(arr)) {
        for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) {
            arr2[i] = arr[i];
        }
        return arr2;
    } else {
        if (!Array.from) {
            Array.from = (function () {
                var toStr = Object.prototype.toString;
                var isCallable = function (fn) {
                    return typeof fn === 'function' || toStr.call(fn) === '[object Function]';
                };
                var toInteger = function (value) {
                    var number = Number(value);
                    if (isNaN(number)) { return 0; }
                    if (number === 0 || !isFinite(number)) { return number; }
                    return (number > 0 ? 1 : -1) * Math.floor(Math.abs(number));
                };
                var maxSafeInteger = Math.pow(2, 53) - 1;
                var toLength = function (value) {
                    var len = toInteger(value);
                    return Math.min(Math.max(len, 0), maxSafeInteger);
                };

                // The length property of the from method is 1.
                return function from(arrayLike/*, mapFn, thisArg */) {
                    // 1. var C be the this value.
                    var C = this;

                    // 2. var items be ToObject(arrayLike).
                    var items = Object(arrayLike);

                    // 3. ReturnIfAbrupt(items).
                    if (arrayLike == null) {
                        throw new TypeError("Array.from requires an array-like object - not null or undefined");
                    }

                    // 4. If mapfn is undefined, then var mapping be false.
                    var mapFn = arguments.length > 1 ? arguments[1] : void undefined;
                    var T;
                    if (typeof mapFn !== 'undefined') {
                        // 5. else
                        // 5. a If IsCallable(mapfn) is false, throw a TypeError exception.
                        if (!isCallable(mapFn)) {
                            throw new TypeError('Array.from: when provided, the second argument must be a function');
                        }

                        // 5. b. If thisArg was supplied, var T be thisArg; else var T be undefined.
                        if (arguments.length > 2) {
                            T = arguments[2];
                        }
                    }

                    // 10. var lenValue be Get(items, "length").
                    // 11. var len be ToLength(lenValue).
                    var len = toLength(items.length);

                    // 13. If Isvarructor(C) is true, then
                    // 13. a. var A be the result of calling the [[varruct]] internal method of C with an argument list containing the single item len.
                    // 14. a. Else, var A be ArrayCreate(len).
                    var A = isCallable(C) ? Object(new C(len)) : new Array(len);

                    // 16. var k be 0.
                    var k = 0;
                    // 17. Repeat, while k < len… (also steps a - h)
                    var kValue;
                    while (k < len) {
                        kValue = items[k];
                        if (mapFn) {
                            A[k] = typeof T === 'undefined' ? mapFn(kValue, k) : mapFn.call(T, kValue, k);
                        } else {
                            A[k] = kValue;
                        }
                        k += 1;
                    }
                    // 18. var putStatus be Put(A, "length", len, true).
                    A.length = len;
                    // 20. Return A.
                    return A;
                };
            }());
        }
        return Array.from(arr);
    }
}

function changeDpiDataUrl(base64Image, dpi) {
    var dataSplitted = base64Image.split(',');
    var format = dataSplitted[0];
    var body = dataSplitted[1];
    var type;
    var headerLength;
    var overwritepHYs = false;
    if (format.indexOf(PNG) !== -1) {
        type = PNG;
        var b64Index = detectPhysChunkFromDataUrl(body);
        // 28 bytes in dataUrl are 21bytes, length of phys chunk with everything inside.
        if (b64Index >= 0) {
            headerLength = Math.ceil((b64Index + 28) / 3) * 4;
            overwritepHYs = true;
        } else {
            headerLength = 33 / 3 * 4;
        }
    }
    if (format.indexOf(JPEG) !== -1) {
        type = JPEG;
        headerLength = 18 / 3 * 4;
    }
    // 33 bytes are ok for pngs and jpegs
    // to contain the information.
    var stringHeader = body.substring(0, headerLength);
    var restOfData = body.substring(headerLength);
    var headerBytes = atob(stringHeader);
    var dataArray = new Uint8Array(headerBytes.length);
    for (var i = 0; i < dataArray.length; i++) {
        dataArray[i] = headerBytes.charCodeAt(i);
    }
    var finalArray = changeDpiOnArray(dataArray, dpi, type, overwritepHYs);
    var base64Header = btoa(String.fromCharCode.apply(String, _toConsumableArray(finalArray)));
    return [format, ',', base64Header, restOfData].join('');
}
function detectPhysChunkFromDataUrl(data) {
    var b64index = data.indexOf(b64PhysSignature1);
    if (b64index === -1) {
        b64index = data.indexOf(b64PhysSignature2);
    }
    if (b64index === -1) {
        b64index = data.indexOf(b64PhysSignature3);
    }
    // if b64index === -1 chunk is not found
    return b64index;
}
function searchStartOfPhys(data) {
    var length = data.length - 1;
    // we check from the end since we cut the string in proximity of the header
    // the header is within 21 bytes from the end.
    for (var i = length; i >= 4; i--) {
        if (data[i - 4] === 9 && data[i - 3] === _P &&
            data[i - 2] === _H && data[i - 1] === _Y &&
            data[i] === _S) {
            return i - 3;
        }
    }
}
function changeDpiOnArray(dataArray, dpi, format, overwritepHYs) {
    if (format === JPEG) {
        dataArray[13] = 1; // 1 pixel per inch or 2 pixel per cm
        dataArray[14] = dpi >> 8; // dpiX high byte
        dataArray[15] = dpi & 0xff; // dpiX low byte
        dataArray[16] = dpi >> 8; // dpiY high byte
        dataArray[17] = dpi & 0xff; // dpiY low byte
        return dataArray;
    }
    if (format === PNG) {
        var physChunk = new Uint8Array(13);
        // chunk header pHYs
        // 9 bytes of data
        // 4 bytes of crc
        // this multiplication is because the standard is dpi per meter.
        dpi *= 39.3701;
        physChunk[0] = _P;
        physChunk[1] = _H;
        physChunk[2] = _Y;
        physChunk[3] = _S;
        physChunk[4] = dpi >>> 24; // dpiX highest byte
        physChunk[5] = dpi >>> 16; // dpiX veryhigh byte
        physChunk[6] = dpi >>> 8; // dpiX high byte
        physChunk[7] = dpi & 0xff; // dpiX low byte
        physChunk[8] = physChunk[4]; // dpiY highest byte
        physChunk[9] = physChunk[5]; // dpiY veryhigh byte
        physChunk[10] = physChunk[6]; // dpiY high byte
        physChunk[11] = physChunk[7]; // dpiY low byte
        physChunk[12] = 1; // dot per meter....

        var crc = calcCrc(physChunk);

        var crcChunk = new Uint8Array(4);
        crcChunk[0] = crc >>> 24;
        crcChunk[1] = crc >>> 16;
        crcChunk[2] = crc >>> 8;
        crcChunk[3] = crc & 0xff;

        if (overwritepHYs) {
            var startingIndex = searchStartOfPhys(dataArray);
            dataArray.set(physChunk, startingIndex);
            dataArray.set(crcChunk, startingIndex + 13);
            return dataArray;
        } else {
            // i need to give back an array of data that is divisible by 3 so that
            // dataurl encoding gives me integers, for luck this chunk is 17 + 4 = 21
            // if it was we could add a text chunk contaning some info, untill desired
            // length is met.

            // chunk structur 4 bytes for length is 9
            var chunkLength = new Uint8Array(4);
            chunkLength[0] = 0;
            chunkLength[1] = 0;
            chunkLength[2] = 0;
            chunkLength[3] = 9;

            var finalHeader = new Uint8Array(54);
            finalHeader.set(dataArray, 0);
            finalHeader.set(chunkLength, 33);
            finalHeader.set(physChunk, 37);
            finalHeader.set(crcChunk, 50);
            return finalHeader;
        }
    }
}

**Comment by DhawalK09** [comment]
hi @asturur sorry for late revert.
I did this
`var Base64= canvas.toDataURL('image/png', 0.92)
var daurl300dpi = changeDpiDataUrl(Base64, 300);
var link = document.createElement("a");
link.setAttribute("style", "display:none;");
link.download = "chart.png";
link.href=daurl300dpi ;
link.click();
`

I'm able to get 300 DPI for 'image/jpeg' but when i did "canvas.toDataURL('image/png', 0.92)" It returns only 96 DPI Image.
Please help me out with this.
Thanks.

I changed a bit to main code as i was having issue with my js minification due to const and let so i changed it to var

**Comment by DhawalK09** [comment]
hi @asturur 
any help would be appreciated.

**Comment by DhawalK09** [comment]
Hello sir, could you please help me out with this.
Thanks.

**Comment by asturur** [comment]
Hi @DhawalK09  i ll set up some time today to test it again.
How are you inspecting the dpis? what software are you using?

Also can  you give me a base64 you use for testing?

thanks.

**Comment by DhawalK09** [comment]
Hi @asturur Thanks a huge for quick revert.
I'm inspecting DPI using Paint app's Property. (As our clients do using paint).

and below is base64 and image after export.
var base64= uri.toDataURL('image/png', 0.92); //uri is canvas

[PNGBase64.txt](https://github.com/shutterstock/changeDPI/files/2919325/PNGBase64.txt)
![column](https://user-images.githubusercontent.com/31307938/53637399-0ecb6280-3c49-11e9-936b-266c6be42f11.png)

**Comment by asturur** [comment]
while i try it, can you check with windows rightclick `preview`,  or macos Preview app the value of the DPI. I remember paint not being the best tool out there.

**Comment by DhawalK09** [comment]
I checked earlier itself it's 300 DPI out there in windows rightclick but as i told you it's about client's requirement they check it through paint.
for jpeg it's 300 in paint but for png I'm unlucky.

**Comment by asturur** [comment]
so i cannot help that much, looks like paint does not work?

**Comment by DhawalK09** [comment]
Alright no issues.
Thanks a huge for your response.
